swiftmailer:
    transport:        gmail
    username:         mohamedsaiche.kbm@gmail.com
    password:         saiche+123
    host:             mail.gmail.com
    port:             465
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false